#!/usr/bin/env python3
# Copyright 2026 Virdyn Robotics

"""Run the installed M20 boundary-recovery probe."""

from m20_warehouse_inspection.boundary_recovery_probe import main


if __name__ == '__main__':
    raise SystemExit(main())
