#!/usr/bin/env python3
# Copyright 2026 Virdyn Robotics
#
# Licensed under the Apache License, Version 2.0.

"""Start the M20 safety supervisor."""

from m20_inspection_core.safety_supervisor_node import main


if __name__ == '__main__':
    main()
