/**:
  ros__parameters:
    use_sim_time: false
    quadrotor_name: m20/sensing
    sensor_type: lidar
    body_pose_topic: /m20/sim/body_pose
    map.resolution: 0.10
    map.x_size: 40.0
    map.y_size: 40.0
    map.z_size: 3.0
    sensing_horizon: 20.0
    sensing_rate: 10.0
    estimation_rate: 10.0
    polar_resolution: 0.5
    yaw_fov: 360.0
    vertical_fov: 70.0
    min_raylength: 0.20
    downsample_res: 0.10
    lidar_pitch: 0.0
    is_360lidar: 1
    use_minicf_pattern: 1
    use_avia_pattern: 0
    use_vlp32_pattern: 0
    use_os64_pattern: 0
    use_os128_pattern: 0
    cam_width: 640
    cam_height: 480
    cam_fx: 387.229248046875
    cam_fy: 387.229248046875
    cam_cx: 321.04638671875
    cam_cy: 243.44969177246094
    dynamic.enable: 0
    dynamic.object_size: 0.0
    dynamic.object_count: 0
    dynamic.mode: 0
    dynamic.velocity: 0.0
    collision_check.enable: 1
    collision_check.range: 0.28
    use_global_map_topic: true
    pcd_map_file: ''
