# 当前默认使用官方 M20 场景的项目内副本。
m20_factory_simulation:
  ros__parameters:
    use_viewer: true
    initial_x: 0.0
    initial_y: 0.0
    initial_z: 0.2
    initial_yaw: 1.57
    render_interval: 50
    enable_drdds_bridge: true
    publish_ground_truth_odom: true
    publish_tf: true
    use_ros_time_stamp: true
    odom_topic: /odom
    odom_frame_id: odom
    base_frame_id: base_link
