#!/usr/bin/env python3
# Copyright 2026 Virdyn Robotics
#
# Licensed under the Apache License, Version 2.0.

"""Start the M20 motion-intent and SDK command adapter."""

from m20_nav2_locomotion.locomotion_manager_node import main


if __name__ == '__main__':
    main()
