#!/usr/bin/env python3
# Copyright 2026 Virdyn Robotics
# Licensed under the Apache License, Version 2.0.

"""Import a surveyed PCD into the real-site map asset contract."""

from m20_warehouse_inspection.cli import main_import_site_pcd


if __name__ == '__main__':
    raise SystemExit(main_import_site_pcd())
