#!/usr/bin/env python3
# Copyright 2026 Virdyn Robotics

"""Run the installed M20 command-envelope probe."""

from m20_warehouse_inspection.command_envelope_probe import main


if __name__ == '__main__':
    raise SystemExit(main())
