#!/usr/bin/env python3
# Copyright 2026 Virdyn Robotics
#
# Licensed under the Apache License, Version 2.0.

"""Start the M20 RViz kinematic backend."""

from m20_warehouse_sim.kinematic_backend_node import main


if __name__ == '__main__':
    main()
