#!/usr/bin/env python3
# Copyright 2026 Virdyn Robotics
#
# Licensed under the Apache License, Version 2.0.

"""Executable wrapper for the M20 grid route planner."""

from m20_scan_navigation.grid_route_node import main


if __name__ == '__main__':
    main()
